### ISSUE TITLE
FARMING - Upgrade Node features

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#102]
- [ ] 

![image](https://user-images.githubusercontent.com/61866569/90008957-7b9bb680-dc9d-11ea-9762-dff4db6ce613.png)
This whole section needs to be replaced by this:
https://drive.google.com/file/d/1_hzxm0xTv3FxSqF4yvC8G-RveazCPVXv/view?usp=sharing

- [x] remove the whole section along with the features underneath "CHARACTERISTICS OF THE LARGEST DECENTRALIZED INTERNET GRID"

**Comment by maximilianrang** [comment]
- [x] link DIY button to https://manual.threefold.io/#/v2_jsx_farmsetup

**Comment by samaradel** [comment]
The layout is done... it needs to fill images placeholders.
