### ISSUE TITLE
HOME - minor text change

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#105]
- [x] Decentralised storage and compute owned by everyone, everywhere.
-> Decentralized storage and compute owned by everyone, everywhere.

**Comment by BenjellounO** [comment]
Here are some suggestions, @maximilianrang  what do you think? 

- [ ] Decentralized compute, storage, and networking, owned by everyone, everywhere 

- [ ] Decentralized cloud capacity owned by everyone, everywhere

- [ ] Powering the next generation of applications with decentralized computing, storage, and networking 

- [x] Powering Web2 and Web3 applications with **decentralized cloud computing**, owned by everyone, everywhere.

**Comment by maximilianrang** [comment]
Decentralised storage and compute owned by everyone, everywhere.
-> Decentralized storage and compute owned by everyone, everywhere.

just that one please :)
