### ISSUE TITLE
FARMING - Update button

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#112]
The button under Mazraa in several locations
![image](https://user-images.githubusercontent.com/61866569/90226676-9ee87200-de13-11ea-83f9-9fb8f06593e1.png)

should link to:
https://www.farmer.threefold.io/small-threefold-nodes.html

**Comment by Vilnite** [comment]
Both purchase links on Farming page updated.

**Comment by andhartl** [comment]
thx
