### ISSUE TITLE
PARTNERS - Add testimonials according to ZIAs layout

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#120]
![image](https://user-images.githubusercontent.com/61866569/90630953-3427a400-e222-11ea-9847-b9aeedbd00b1.png)

3 final quotes will be provided here until tomorrow noon:
https://docs.google.com/document/d/1xja7ifeQbE5edZaFCZGmCMVPJAXdynfRMDlbhlcSJ4Y/edit

**Comment by maximilianrang** [comment]
- [x] please also change this text:
Together we build the new Internet
-> Welcome to the growing ecosystem around ThreeFold

**Comment by samaradel** [comment]
testimonials added

**Comment by BenjellounO** [comment]
3 testimonials added to the doc: https://docs.google.com/document/d/1xja7ifeQbE5edZaFCZGmCMVPJAXdynfRMDlbhlcSJ4Y/edit
To be inserted in the "partners page @ehab-hassan  @samaradel

**Comment by samaradel** [comment]
@BenjellounO can you update testimonials with logos please

**Comment by maximilianrang** [comment]
![image](https://user-images.githubusercontent.com/61866569/91023612-0dd58000-e5f7-11ea-9692-b2a1df0e052b.png)

- [x] please make sure the vertical distance between lines is respected. Does not work with the big distance before "SKALE LABS" etc.

- [x] Please implement the logos for SKALE, PRESEARCH and DIGIBYTE accordingly.

**Comment by maximilianrang** [comment]
- [x] change PRESEARCH text to: 

Threefolds distributed infrastructure offering peer-to-peer storage and compute resources paid with cryptocurrency is exactly what the project needs to fulfil our roadmap and decentralize the platform.

**Comment by maximilianrang** [comment]
- [x] one final thing to make it perfect:
Please make quotation marks around the quotes and change the font to _italic_
