### ISSUE TITLE
NavBar is not optimised for 13" MacBook Pro Safari

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#127]
<img width="1440" alt="Screenshot 2020-08-26 at 15 13 37" src="https://user-images.githubusercontent.com/54844940/91307818-baa62d80-e7ae-11ea-9607-2c70bd9ea7dc.png">

ABOUT US takes two lines ...

**Comment by Sacha96** [comment]
Also Deploy Beta Tokens is not on same line as rest of NAVBAR - weird visually

**Comment by samaradel** [comment]
@Sacha96, please check [staging](https://www2.threefold.io/) in private window

**Comment by Sacha96** [comment]
still the same on staging @samaradel

**Comment by Sacha96** [comment]
@samaradel @ehab-hassan I discussed with @maximilianrang and we can remove "US" from "ABOUT US". So only "ABOUT" is displayed - saves space on navbar and ensures it fits screen across browsers.

**Comment by Sacha96** [comment]
Also "DEPLOY" and "BETA" is not on same line gradient
