### ISSUE TITLE
Add "HOME" on far left of NAVBAR

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#132]

**Comment by ehab-hassan** [comment]
![ThreeFold](https://user-images.githubusercontent.com/10484295/91822218-b9a24f80-ec37-11ea-9be9-8d14b937cb9c.png)
It ll not be good to but link alone at left and we already have home at logo, if it necessary to put so reasonable to be with other links at right

**Comment by Sacha96** [comment]
Meant to put left next to FARMING

**Comment by ehab-hassan** [comment]
done at staging
