### ISSUE TITLE
changes to "THE FEATURES OF THREEFOLD GRID" section

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#137]
1. change the MAIN TITLE 

current: THE FEATURES OF THREEFOLD GRID
new: FEATURES OF THE THREEFOLD GRID

2. AN INTERNET FOR EVERYONE text change 
current: With merely a source of energy, a network and the 3Node, access to the internet becomes a reality for every human being on the planet.
new: With merely an energy source, a network, and a 3Node needed, the ThreeFold Grid brings the possibility of Internet access to everyone, everywhere.

<img width="1416" alt="Screenshot 2020-09-01 at 10 12 02" src="https://user-images.githubusercontent.com/54844940/91824893-c45ee380-ec3b-11ea-8cfb-e7ceae5de7f6.png">

3. BY EVERYONE section 

current text: The new internet is common good owned by all of us. Everyone is invited to become a farmer and host the hardware that is the backbone of this new peer-to-peer internet.
new text: The new Internet is a common good owned by all of us. Everyone is invited to become a farmer, to deploy and develop, and to use applications on this new peer-to-peer Internet. 

**Also developer demographic is missing**
There are Farmers + Users ... but no ... developers. 

current: FARMERS link their 3Nodes..... 
current: USERS access decentralized .... 
Add: DEVELOPERS own 100% of their workloads via a smart contract for IT

**Comment by Sacha96** [comment]
Once we move User part a little bit to the right - we good

**Comment by ehab-hassan** [comment]
done
