### ISSUE TITLE
Improve Sign Up process

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#139]
<img width="514" alt="Screenshot 2020-09-01 at 10 49 02" src="https://user-images.githubusercontent.com/54844940/91828747-cd9e7f00-ec40-11ea-89c3-c82810222d56.png">

Bring below box (without title) under text ^^. Then keep 2 buttons under. So that people can sign up directly from the main page. 

<img width="565" alt="Screenshot 2020-09-01 at 10 48 56" src="https://user-images.githubusercontent.com/54844940/91828754-cecfac00-ec40-11ea-9cd6-9c00225f7021.png">

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/91838455-d6e21880-ec4d-11ea-92ec-4aebdb0a5324.png)
Its an embed form I can't add signup button beside telegram button

**Comment by Sacha96** [comment]
can we have telegram button like sign up button on last image ^^ and just add "AND" between both boxes?

**Comment by samaradel** [comment]
Displayed on staging

**Comment by Sacha96** [comment]
Can we make the section a bit smaller (same size as before if we can while keeping buttons in)?

**Comment by maximilianrang** [comment]
Instead of "AND" Telegram
-> "AND JOIN US ON" Telegram

**Comment by ehab-hassan** [comment]
fixed
