### ISSUE TITLE
Bring back "our whys" to ABOUT page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#141]
WE got the feedback that the ABOUT page didn't have the people behind the project. 

Let's bring back OUR WHYS section (like on https://www.threefold.me/vision.html) to ABOUT page on threefold.io

<img width="1164" alt="Screenshot 2020-09-01 at 10 57 03" src="https://user-images.githubusercontent.com/54844940/91829600-f5421700-ec41-11ea-85da-e12ffa2e0f95.png">

**Comment by ehab-hassan** [comment]
I add this section at above of road-map
