### ISSUE TITLE
Make sure "TITLE" & "GRAPHIC" SIZE is consistent across pages

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#142]
https://threefold.io/public/#/partners has bigger TITLE size and very small GRAPHIC size as compared to other pages. 

Lets make it more consistent 

i.e. make font size same then on other pages' titles + increase design size to match other pages intro...

**Comment by ehab-hassan** [comment]
we made this design according to this issue https://github.com/threefoldfoundation/www_tfgrid/issues/120 by @maximilianrang 
they need testimonials at header 
so put testimonials blow the header banner ?

**Comment by maximilianrang** [comment]
Just changing the fontsize should work.

**Comment by ehab-hassan** [comment]
font size updated

**Comment by Sacha96** [comment]
Increase size of current graphic @ partner page by about 50% and cut spacing between text and testimonials by 1/2
