### ISSUE TITLE
Smart Contract for IT text on home needs to be updated

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_cloud_threefold.io#145]
<img width="573" alt="Screen Shot 2020-09-08 at 7 11 33 PM" src="https://user-images.githubusercontent.com/50134479/92501397-294fa600-f207-11ea-876a-405cb4fa9939.png">

@andhartl recommends that we update the text to say:

"and Smart Contract for IT technology manages all workloads."

**Comment by ehab-hassan** [comment]
done
