### ISSUE TITLE
DEPLOY - Updates to Testnet  (staging)

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#154]
![image](https://user-images.githubusercontent.com/61866569/95085198-2c16bb80-071f-11eb-84a2-ecd96a3759bf.png)
This part needs an update to reflect 3Bot deployment.

- [x] DECENTRALIZE YOUR APPLICATION -> DEPLOY ON THE THREEFOLD GRID

- [x] Download and install the 3Bot application to move your workload over today.
-> ...via 3Bot, your virtual system administrator.

- [x] install
the 3Bot
application
-> 
Install the 3Bot Connect mobile app.

- [x] 2
Launch
The ThreeFold Marketplace
-> 
2
Deploy your virtual system administrator on the ThreeFold Grid.

- [ ] 
![image](https://user-images.githubusercontent.com/61866569/95085956-2e2d4a00-0720-11eb-9531-39ed44d92985.png)
-> DEPLOY 3BOT
(remove BETA from button)
deploy3bot.testnet.grid.tf

- [x] add section 3 with the old TFT image we had and removed for step 2 in a previous version of the website.
![image](https://user-images.githubusercontent.com/61866569/95086274-9419d180-0720-11eb-9718-c6be5a2418f4.png)
->
3
Get FreeTFT on Testnet
Button: FreeTFT Faucet 
gettft.testnet.grid.tf

**Comment by maximilianrang** [comment]
A few minor changes:

- [ ] 
![image](https://user-images.githubusercontent.com/61866569/95300485-82027500-087f-11eb-9445-5b4ffe81179b.png)
move linebreak to after "Connect"

![image](https://user-images.githubusercontent.com/61866569/95300572-a65e5180-087f-11eb-8f94-5f136d8a42aa.png)

- [x] "your virtual system administrator on the ThreeFold Grid." ->"your virtual system administrator on the ThreeFold Grid Testnet."

![image](https://user-images.githubusercontent.com/61866569/95300661-bfff9900-087f-11eb-96b9-4dedfd5da643.png)

- [x] GET
FreeTFT on Testnet 
-> 
CLAIM 
your FreeTFT for testing purposes.

**Comment by ehab-hassan** [comment]
done at staging

**Comment by maximilianrang** [comment]
<img width="368" alt="Screenshot 2020-10-19 at 11 17 44" src="https://user-images.githubusercontent.com/61866569/96425821-bae60680-11fc-11eb-846f-a6f7d6829fb0.png">

- [x] add text below GET TFT 
to run almost any application on the ThreeFold Grid.

**Comment by maximilianrang** [comment]
one last change
<img width="918" alt="Screenshot 2020-10-19 at 15 16 24" src="https://user-images.githubusercontent.com/61866569/96455874-12489e80-121e-11eb-86dd-727385d85f54.png">

- [ ] "application" -> "Connect mobile app"

- [ ] then push to production
