### ISSUE TITLE
DEPLOY - Updates (live)

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#159]
Section: Applications

<img width="240" alt="Screenshot 2020-10-19 at 16 31 01" src="https://user-images.githubusercontent.com/61866569/96464796-8ab45d00-1228-11eb-843a-ac8cfd122615.png">
- [ ] ThreeFold grid -> ThreeFold Grid 

- [x] Section: planet friendly
 No more enterprise service buses -> No more enterprise service busses

**Comment by samaradel** [comment]
text updated on staging

**Comment by ehab-hassan** [comment]
done at production
