### ISSUE TITLE
TEAM - add new member: Andrea Castiglione

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#167]
**Andrea Castiglione**

For over a decade, Andrea has been working at the crossroad of technology, entrepreneurship and human relationships. Coming from a deeply analytical background, he has started multiple businesses and began investing in what he defines “digital emerging markets”, which in all essence, are companies designed to be digital and borderless; not bound by geography. 
As a venture builder, Andrea believes it’s time to reinvent the very architecture of the internet and he’s ready to support Threefold in distributing its technology and values through his experience and a global network of partners.

https://www.linkedin.com/in/castiglioneand/

![image-removebg-preview (3)](https://user-images.githubusercontent.com/61866569/97975141-ed7d2b00-1dc8-11eb-80de-5e0a6e666c7e.png)

**Comment by ehab-hassan** [comment]
done
