### ISSUE TITLE
ThreeFold Now - Responsiveness issue 

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#171]
​​​​
![image](https://user-images.githubusercontent.com/61866569/98349235-07617c80-201a-11eb-84de-0f8ce64ef408.png)

Can we prevent that the button overlaps the darker background? If not, can we have it change its colour to white when overlapping?

**Comment by ehab-hassan** [comment]
in which size that happen?

**Comment by ehab-hassan** [comment]
it's green now according to https://github.com/threefoldfoundation/www_tfgrid/issues/164 so I think it fixed
