### ISSUE TITLE
NEWS - remove dead link (live & staging)

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#174]
<img width="455" alt="Screenshot 2020-11-10 at 14 37 01" src="https://user-images.githubusercontent.com/61866569/98681702-53d2f200-2363-11eb-9d44-7bdf40c56a0a.png">

- [x] we need to remove that section as the article is not available anymore & the link is dead

**Comment by ehab-hassan** [comment]
done
