### ISSUE TITLE
Create new DEPLOY section on staging 

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#26]
Staging will be on www2.threefold.io

Content will be provided via telegram.

All images should be implemented as SVG. No text should be embedded within images. Please create issues and assign @maximilianrang if blockages occur or the mockup cant be replicated within reasonable effort.

**Comment by ehab-hassan** [comment]
deploy page updated at https://www2.threefold.io/deploy.html
still need some enhancement and fix some part at responsive, it'll fix with all pages when it finish
