### ISSUE TITLE
Corrections for NAVBAR 

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#33]
- Please increase fontstyle to match DEPLOY and TOKEN, keep colour
- Please include a link to: https://blog.threefold.io/blog/tfblog/posts?page=1 as BLOG

**Comment by js-threefold** [comment]
Format looks goods. Nav bar text needs to be updated and links added. Image is attached below: 

![Group 18](https://user-images.githubusercontent.com/68718676/88556659-e4710680-cfee-11ea-8c1d-f9fed60508e6.png)

**Comment by js-threefold** [comment]
What is ThreeFold?  --> threefold.io/
What is the ThreeFold Token (TFT)?  --> threefold.io/tokens
Buy TFT --> wiki.threefold.io/#/how_to_buy_and_sell
Become a Farmer --> wiki.threefold.io/#/become_a_farmer
ThreeFold Wiki (knowledgebase) --> wiki.threefold.io/#/
ThreeFold Community --> forum.threefold.io/

Get Started  --> threefold.io/deploy
Solutions  --> marketplace.threefold.me/marketplace/#/
Developer Resources --> sdk.threefold.io/#/
ThreeFold Github --> github.com/threefoldfoundation

ThreeFold Foundation --> threefold.foundation
ThreeFold Forum  --> forum.threefold.io/
Alliance for a Conscious Internet --> consciousinternet.org/
ThreeFold Brand Assets --> wiki.threefold.io/#/threefold_content

About Us  --> threefold.io/about-us
Privacy Policy  --> threefold.io/privacy
Terms & Conditions --> https://docs.google.com/document/u/4/d/e/2PACX-1vQi1xj_YnBd_NaW5BvSWwsfH0JC-1T5WWAL6QhE0SiPmcFT3GtmiiD09Z0gNookT45dHb9iSeyiNchq/pub
Contact --> mailto:press@threefold.io

Facebook  --> https://www.facebook.com/threefold.io
Twitter  --> https://twitter.com/threefold_io
LinkedIn --> https://www.linkedin.com/company/threefold-foundation/
YouTube --> https://www.youtube.com/threefoldfoundation
Telegram --> https://t.me/threefoldnews

**Comment by ehab-hassan** [comment]
(ThreeFold Studio ) is that is Solutions --> marketplace.threefold.me/marketplace/#/ and link not working
Privacy policy link not working
Cookie Policy link not available

**Comment by js-threefold** [comment]
for solutions --> let's remove for now until the marketplace is ready next sprint

for privacy policy --> change to this for now: https://docs.google.com/document/d/1SHLKJBdZHtGrb0p8OnfHUYsMtHPOf4sZPawpPWY8FtU/edit

remove cookie policy from the menu.

**Comment by ehab-hassan** [comment]
done

**Comment by js-threefold** [comment]
Yes, this can be closed except for — www2.threefold.me will need to switch to www.threefold.me when it is ready.

**Comment by js-threefold** [comment]
— I am seeing that these changes are only reflected on the DEPLOY page and need to be made site-wide. 

Additionally, two other quick fixes: 

- "Contect" needs to be changed to "Contact" with an a
- "Developer Resourses" needs to be changed to "Developer Resources" with a c

**Comment by ehab-hassan** [comment]
fixed
