### ISSUE TITLE
Corrections for HOME

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#34]
all items experienced on Chrome, Mac, 4K resolution.

- [x] in general: Please fix all typos.
 - THE FUTURES OF THREEFOLD
 - INTRODUCING DECENTERALIZED STORAGE AND COMPUTE. 
- Kubernates (several times spelled wrong)

- [x] "INTRODUCING DECENTRALIZED STORAGE AND COMPUTE" Please change font sizes and distance between lines of the headline as provided in the AI file.
- [x] "POWERING THE NEW INTERNET WITH OUR OWN OPERATING SYSTEM" Please change distance between lines of the headline as provided in the AI file.
- [x] increase image size at "INTRODUCING DECENTRALIZED STORAGE AND COMPUTE" and reduce the whitespace underneath.
- [x] Decrease font size of * text next to HP logos to +-40% and also reduce distance between lines by an additional +-50%.
- [x] Button "Become a Farmer" should link to farmer.threefold.io
- [x] "WE ARE LIVE" map: "Active nodes in 16 countries" should match the fontstyle of "CPU CORES"
- [x] "WE ARE LIVE" map: + and - button don't scale properly and are too large at the moment.
- [x] "DEPLOY YOUR APPLICATION" button: should link to DEPLOY
- [x] "BY EVERYONE" please adjust the line distance of the text below to match the AI file. The image below needs to be in higher resolution with 4K width.
- [x] "100% compatible with Kubernates, Docker, S3 & Linux." please remove this text and headline
- [x] "IN THE NEWS" please replace images with the ones from AI file
- [x] "WIKI" button  - please link to wiki.threefold.io

**Comment by maximilianrang** [comment]
![Asset 30](https://user-images.githubusercontent.com/61866569/88676141-069c7e80-d0ec-11ea-9ae3-dc08e690504b.png)
Please use this file for the wiki image on the bottom.

**Comment by maximilianrang** [comment]
[ ]
![image](https://user-images.githubusercontent.com/61866569/88801902-a1f42900-d1aa-11ea-97bb-103d8bccad2e.png)

resolution is too small for 4K screen. Please fix.

**Comment by js-threefold** [comment]
- [x] fix Explore Our Wiki link to: wiki.threefold.io

- [x] Become A Farmer link should be: threefold.io/farming

**Comment by scottyeager** [comment]
Some more typos and editing notes:

- [x] "3Nodes form a global *network* of decentralized storage and compute."
- [x] "Any application which can run on **L**inux"
- [x] "*with* more speed, cost-efficiency, privacy & security, sustainability, and more." Besides typo, this phrasing is awkward, especially the "and more", which reads "more more" with the rest of the list removed.
- [x] "loT, 5G, AI*,* and VR/A**R**" The Oxford comma is not necessary (it is my professional preference), of course, but is used in the previous bullet and should probably at least be consistent.
- [x] If Oxford comma is preferred, add here: "With merely a source of energy, a network and the 3Node"
- [x] "the largest and most advanced P2P network continues to expand." Are we larger than bittorrent or tor? Perhaps "P2P _cloud computing_ network".
- [x] Switch non proper nouns "Blockchain" and "Smart Contract" to lower case (actually, "Smart Contract for IT" could be considered a proper noun, but I think that distinction is better saved for terms like "Grid"

More a suggestion than a correction: add "Developers" in the graphic under By Everyone section.

**Comment by maximilianrang** [comment]
![text](https://user-images.githubusercontent.com/61866569/89409581-96f94580-d722-11ea-9b51-44c9cc071ac5.JPG)
this paragraph is still not in the correct layout.

**Comment by Vilnite** [comment]
> Some more typos and editing notes:
> 
> * [x]  "3Nodes form a global _network_ of decentralized storage and compute."
> * [x]  "Any application which can run on **L**inux"
> * [x]  "_with_ more speed, cost-efficiency, privacy & security, sustainability, and more." Besides typo, this phrasing is awkward, especially the "and more", which reads "more more" with the rest of the list removed.
> * [x]  "loT, 5G, AI*,* and VR/A**R**" The Oxford comma is not necessary (it is my professional preference), of course, but is used in the previous bullet and should probably at least be consistent.
> * [x]  If Oxford comma is preferred, add here: "With merely a source of energy, a network and the 3Node"
> * [x]  "the largest and most advanced P2P network continues to expand." Are we larger than bittorrent or tor? Perhaps "P2P _cloud computing_ network".
> * [x]  Switch non proper nouns "Blockchain" and "Smart Contract" to lower case (actually, "Smart Contract for IT" could be considered a proper noun, but I think that distinction is better saved for terms like "Grid"
> 
> More a suggestion than a correction: add "Developers" in the graphic under By Everyone section.

Scotts comments has been addressed and fixed. 
About the largest peer-to-peer network - we reference that way everywhere in the website including titles so I left it as it is for now.
