### ISSUE TITLE
Corrections to FARMING SECTION

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#37]
<img width="1304" alt="Screenshot 2020-07-27 at 09 43 13" src="https://user-images.githubusercontent.com/61866569/88516658-ebe3e000-cfed-11ea-846f-59d2c8f232e5.png">

- [x] We need to make sure the bottom text is formatted identically to the one one the top.

- [x] BUTTON "START BUILDING YOUR 3NODE" needs to link to: https://sdk.threefold.io/#/v2_jsx_farmsetup

- [x] BOTTON "PRE-REGISTER FOR THE NEXT BATCH" needs to link to https://www.farmer.threefold.io/

**Comment by maximilianrang** [comment]
<img width="1312" alt="Screenshot 2020-07-27 at 16 59 49" src="https://user-images.githubusercontent.com/61866569/88557567-a7c30080-d02a-11ea-8f68-56639cddd173.png">
<img width="1135" alt="Screenshot 2020-07-27 at 17 01 56" src="https://user-images.githubusercontent.com/61866569/88557769-ef498c80-d02a-11ea-8617-4edabe00cf92.png">



- [x] please format all 4 text blocks from the screenshots exactly as this section "The ThreeFold Grid is currently distributed across 19 countries, has more than 80 Million GB of storage and over twenty thousand CPU cores live. Become a ThreeFold Farmer and join us in the journey towards true decentralization." Please make sure the boldness and vertical line distance is the same as well as the distance to the headline.

**Comment by ehab-hassan** [comment]
done
