### ISSUE TITLE
Corrections to TOKEN section

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#39]
<img width="1260" alt="Screenshot 2020-07-27 at 13 39 30" src="https://user-images.githubusercontent.com/61866569/88537919-bac7d780-d00e-11ea-8440-27c5d53b5d48.png">
- [ ] we need to make sure the vertical distance from content to button is the same for all three buttons.

- [x] Button TFT SIMULATOR link to https://wiki.threefold.io/#/farming_simulate?id=in-wiki-simulator

- [x] Button GET MORE TFT rename to GET TFT & link to https://wiki2.threefold.io/#/how_to_buy_and_sell

<img width="1896" alt="Screenshot 2020-07-27 at 14 02 50" src="https://user-images.githubusercontent.com/61866569/88539623-e5675f80-d011-11ea-82fb-3f6f9a5bbfca.png">
- [ ] please make sure the group of 4 Items from "Pre Launch" until "20,000 +" is aligned to the middle if the screen

- [x] remove space between "20,000" and "+" so "20,000+"

- [x] usd 59M + item is editable. This needs to be fixed.

**Comment by maximilianrang** [comment]
UPDATE: Please leave out this part at this point. We need to define new stats:
<img width="1424" alt="Screenshot 2020-07-27 at 14 02 38" src="https://user-images.githubusercontent.com/61866569/88543208-edc29900-d017-11ea-982d-ba070f517b8c.png">

**Comment by maximilianrang** [comment]
![Tokenomics](https://user-images.githubusercontent.com/61866569/88676341-3cd9fe00-d0ec-11ea-8774-f6ca1b368a9f.png)
Updated image for token stats.

**Comment by ehab-hassan** [comment]
done

**Comment by maximilianrang** [comment]
- [ ] 
![image](https://user-images.githubusercontent.com/61866569/88802257-1929bd00-d1ab-11ea-9dda-339e9cc7353f.png)
resolution is too small for 4K.

- [ ] 
<img width="658" alt="Screenshot 2020-07-29 at 14 53 12" src="https://user-images.githubusercontent.com/61866569/88802378-470f0180-d1ab-11ea-95bd-783375afaf3b.png">
Please equalize distances between headlines, text and button of the second paragraph to match the first.

**Comment by maximilianrang** [comment]
resolution of Token circular graphic is still a bit low, the rest is good

**Comment by ehab-hassan** [comment]
done
