### ISSUE TITLE
Provide a list of use-cases and logos as vector

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#40]
<img width="803" alt="Screenshot 2020-07-27 at 14 07 34" src="https://user-images.githubusercontent.com/61866569/88540794-e4373200-d013-11ea-8c23-2e2e1ada9b1e.png">
We need to provide the logos from these use cases as vectors.

**Comment by BenjellounO** [comment]
@maximilianrang here's the list of confirmed Blockchain partners with their logos https://drive.google.com/drive/folders/17n_Em8mX0ekPR39PfkHfatX4G6pPO6c7?usp=sharing
