### ISSUE TITLE
Fix DEPLOY page on mobile

### ISSUE THREAD

**Issue by js-threefold** [threefoldfoundation/www_cloud_threefold.io#44]

**Comment by js-threefold** [comment]
Edits to the mobile responsiveness of the Deploy page. See attached screenshots and notes below each.

![photo_2020-07-28 12 42 42](https://user-images.githubusercontent.com/68718676/88663438-36726480-d0a1-11ea-907a-fddcb6488263.jpeg)
![photo_2020-07-28 12 42 40](https://user-images.githubusercontent.com/68718676/88662419-8ea86700-d09f-11ea-8cf9-99cd8375eab7.jpeg)

- Reduce "Your Benefits" text/graphic by 30%-50% so that it matches the title text size for rest of the section titles
- Increase title size to be larger than the text below it
- Remove space between rows to make equal

![photo_2020-07-28 12 42 34](https://user-images.githubusercontent.com/68718676/88663429-35413780-d0a1-11ea-8cc7-10ff00f7df3c.jpeg)
![photo_2020-07-28 12 42 31](https://user-images.githubusercontent.com/68718676/88662423-8fd99400-d09f-11ea-96a9-e20c97300ce0.jpeg)
![photo_2020-07-28 12 42 33](https://user-images.githubusercontent.com/68718676/88662424-8fd99400-d09f-11ea-8a7d-a6639a01a0ab.jpeg)
![photo_2020-07-28 12 42 32](https://user-images.githubusercontent.com/68718676/88662425-90722a80-d09f-11ea-8c57-c8ff8a9387a2.jpeg)
![photo_2020-07-28 12 42 29](https://user-images.githubusercontent.com/68718676/88662430-910ac100-d09f-11ea-9776-105bb2dc32db.jpeg)

- Increase title size and text below it about 1.5x 
- Decrease icon sizes 50% 
- Add line space between "Exploration Mode" and the regular text that should go underneath


![photo_2020-07-28 12 42 28](https://user-images.githubusercontent.com/68718676/88662427-90722a80-d09f-11ea-83a6-4831a6c10310.jpeg)

- Decrease graphic size by 50% 


![photo_2020-07-28 12 42 24](https://user-images.githubusercontent.com/68718676/88662433-910ac100-d09f-11ea-9050-34742de54bc2.jpeg)

- Add line space after each column so that spacing is even — should be more 2 lines between last link in each column and the start of the next column


![photo_2020-07-28 12 42 27](https://user-images.githubusercontent.com/68718676/88662434-91a35780-d09f-11ea-99bc-a1f9b8b22618.jpeg)

- Decrease table size to fit the screen (doesn't need to scroll left-right)
- Fix font sizes so that the table fits and is readable 

![photo_2020-07-28 12 42 26](https://user-images.githubusercontent.com/68718676/88662436-91a35780-d09f-11ea-8a4c-a52739775d4c.jpeg)

- Change line space for the text under the title Planet Friendly to 1x
- Increase the size of the graphic to be readable on mobile

![photo_2020-07-28 12 42 36](https://user-images.githubusercontent.com/68718676/88663425-34a8a100-d0a1-11ea-99a2-9c99a210f93e.jpeg)

- Remove extra spacing between sections

![photo_2020-07-28 12 42 43](https://user-images.githubusercontent.com/68718676/88663432-35d9ce00-d0a1-11ea-87cc-f496ed71095c.jpeg)

- Remove extra spacing above "Your Benefits" 
- Decrease font size / graphic image by 30-50% to match title text sizes


![photo_2020-07-28 12 42 37](https://user-images.githubusercontent.com/68718676/88663434-35d9ce00-d0a1-11ea-8ed7-8b83d4ee8ddf.jpeg)

- Reduce image size by 50% 



![photo_2020-07-28 12 42 46](https://user-images.githubusercontent.com/68718676/88663437-36726480-d0a1-11ea-9f14-ff0726aef20d.jpeg)

- Increase header image size to fill the header space
- Add white header bar so that ThreeFold logo is visible (like on desktop) 
- Increase title text size "Own 100% of your deployments...." so that it's larger than the text underneath it

**Comment by ehab-hassan** [comment]
over all fixed expect :
Decrease icon sizes 50% at DECENTRALIZE YOUR APPLICATION section it affect at border and not centered may be check it later 
table cant fit at all image to responsive with all size  so I made sliding and small size ll not readable

**Comment by js-threefold** [comment]
Okay, thanks Ehab — for the icon sizes at Decentralize Your Application are you able to reduce at all? They should be centered and about 30-50% smaller. 

For the table, just remove the row that shows "168" several times in boxes. Should also be removed from desktop version.

Additionally, in that same section please make the "Apply Now" button the same length as the App Store and Google Play buttons for consistency. The rest of it I think looks pretty good for this sprint!
