### ISSUE TITLE
Fix FARMING section on mobile

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#45]
- [ ] 
<img width="695" alt="Screenshot 2020-07-28 at 12 04 14" src="https://user-images.githubusercontent.com/61866569/88652269-e27c7580-d0ca-11ea-9125-6d0f633c8ee4.png">
the graphic needs to be scaled to 300% of current size.

- [ ] 
<img width="352" alt="Screenshot 2020-07-28 at 12 08 03" src="https://user-images.githubusercontent.com/61866569/88652365-050e8e80-d0cb-11ea-9f94-93098dba7335.png">
the vertical distance between the icons and the headlines of the features need to be increased to 80% of the distance between the headlines and the respective text below.

**Comment by ehab-hassan** [comment]
done
