### ISSUE TITLE
Replace BLOG navbar item with INFO

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#49]
The INFO navbar item should be an expandable menu like on current/old threefold.io.
I should include the following items:

- BLOG (link to blog)
- FORUM (link to forum.threefold.io)
- WIKI (link to wiki)
- IN THE NEWS

**Comment by samaradel** [comment]
@maximilianrang IN THE NEWS link should redirect to home page ==> in the news part or to a different page?

**Comment by maximilianrang** [comment]
@samaradel it should be a copy of this page, ofc with our new header and footer.https://www.threefold.io/news.html

**Comment by maximilianrang** [comment]
https://www2.threefold.io/farming.html navbar items INFO dissappears when switching to this page.

**Comment by samaradel** [comment]
please try again in an incognito window

**Comment by maximilianrang** [comment]
still happens also in incognito CHROME, MAC.
