### ISSUE TITLE
Implement Open Graph images

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#61]
![Asset 2](https://user-images.githubusercontent.com/61866569/89192090-27f5e280-d5a4-11ea-87d0-5082fab012a2.png)
![Asset 1](https://user-images.githubusercontent.com/61866569/89192095-2a583c80-d5a4-11ea-90db-974ace7d60f2.png)

Those image files should be updated to be displayed as Open Graph when the website is shared on social or telegram.

**Comment by maximilianrang** [comment]
open graph description:
**THREEFOLD | THE LARGEST PEER-TO-PEER GRID ON THE PLANET.**
Decentralized storage and compute for everyone, owned by everyone, everywhere.

**Comment by ehab-hassan** [comment]
done it reflect when go production

**Comment by maximilianrang** [comment]
is there any way to confirm on development?

**Comment by ehab-hassan** [comment]
![-20-Home-Twitter](https://user-images.githubusercontent.com/10484295/89513380-c8324e00-d7d4-11ea-91a7-ca3bb763bb13.png)
![Facebook](https://user-images.githubusercontent.com/10484295/89513388-c9fc1180-d7d4-11ea-9c26-d4f551ca56d7.png)


u can check it at facebook or twitter  and telegram
