### ISSUE TITLE
Feedback on Mobile version

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_cloud_threefold.io#64]
About section always goes first (who we are, what this is about):

![Screenshot 2020-08-04 at 11 24 07](https://user-images.githubusercontent.com/20182572/89273813-bcb21c00-d648-11ea-88e2-59cc791ac9cf.png)

![Screenshot 2020-08-04 at 11 26 19](https://user-images.githubusercontent.com/20182572/89273879-d3f10980-d648-11ea-8080-806629be04c3.png)

![Screenshot 2020-08-04 at 11 28 29](https://user-images.githubusercontent.com/20182572/89273929-e53a1600-d648-11ea-9a4e-7311ae2304e6.png)

![Screenshot 2020-08-04 at 11 30 42](https://user-images.githubusercontent.com/20182572/89273962-ef5c1480-d648-11ea-94ed-ad8860177938.png)

![Screenshot 2020-08-04 at 11 31 50](https://user-images.githubusercontent.com/20182572/89273983-f551f580-d648-11ea-81e8-92b9ffdeacad.png)

![Screenshot 2020-08-04 at 11 33 54](https://user-images.githubusercontent.com/20182572/89273993-faaf4000-d648-11ea-892a-4a876d2efc19.png)

![Screenshot 2020-08-04 at 11 36 06](https://user-images.githubusercontent.com/20182572/89274016-03077b00-d649-11ea-8c31-58b50065a00a.png)

![Screenshot 2020-08-04 at 11 37 36](https://user-images.githubusercontent.com/20182572/89274047-10246a00-d649-11ea-8f47-c1c226ac2a32.png)

![Screenshot 2020-08-04 at 11 43 16](https://user-images.githubusercontent.com/20182572/89274074-17e40e80-d649-11ea-96f9-2f6e3b1b86bd.png)

**Comment by maximilianrang** [comment]
resolved or redistributed to other issues.
