### ISSUE TITLE
HOME Call to action section

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#69]
we need an additional section for collecting emails and linking to telegram. 
It would be placed above the WIKI section.

The AI file is provided via Telegram.

This is the flow for collecting the email:
![image](https://user-images.githubusercontent.com/61866569/89410152-7da4c900-d723-11ea-9af3-960c4a7c03bf.png)
![image](https://user-images.githubusercontent.com/61866569/89410130-767dbb00-d723-11ea-9b93-c199104c219d.png)

**Comment by ehab-hassan** [comment]
what we for collecting mail(sign up) something like mailchimp?

**Comment by ehab-hassan** [comment]
what is the priority of this issue because it ll take some time ?

**Comment by samaradel** [comment]
mailerlite form added, it needs to add to a group it's in 'test' now

**Comment by maximilianrang** [comment]
![image](https://user-images.githubusercontent.com/61866569/89539222-cc259680-d7fb-11ea-8674-39b0f61989be.png)
can you move the popup window to the center of the screen?

**Comment by samaradel** [comment]
it's an element inside iframe I can't access.
