### ISSUE TITLE
TEAM - create new subpage (copy from current/old threefold.io)

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#75]
- [x] the new subpage should live under INFO in the header.

- [ ] please make sure all logos are SVGs. Connect with @samtaggart for this.

**Comment by ehab-hassan** [comment]
done live under info
(please make sure all logos are SVGs. Connect with @samtaggart for this.) this is the same issue here https://github.com/threefoldfoundation/www_tfgrid/issues/62 logo related to partners page no logos at team page
