### ISSUE TITLE
HOME - find more actionable headline

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#76]
![image](https://user-images.githubusercontent.com/61866569/89451532-a7c6ad00-d75c-11ea-91a5-5a2593c019dc.png)
"STAY IN TOUCH!" is too soft, we need it to be much stronger.
Please add your suggestion as a comment to close this issue.

**Comment by Karoline888** [comment]
e.g. "TAKE ACTION!"

**Comment by samtaggart** [comment]
- ENTER THE FOLD
- TAKE ACTION (as Karoline suggested – could be but it's not super direct)
- STAY IN THE FOLD
- STAY UPDATED
- STAY INFORMED
- STAY IN THE KNOW

**Comment by maximilianrang** [comment]
lets go with TAKE ACTION. @Vilnite can you update the text?

**Comment by Vilnite** [comment]
Done
