### ISSUE TITLE
Change Team page texts 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_cloud_threefold.io#77]
Function IDs should now be displayed as 

1. Team
2. Contributors 
2. Ambassadors 

So Developers >> Contributors 

@Sacha96 will ensure the right people are attributed the right function ID.

@Vilnite can you work out the sub-texts? 

Many thanks team

**Comment by maximilianrang** [comment]
just edited the description, first category should be Employees instead of Team.

**Comment by Vilnite** [comment]
Employees are at corporations. We are a TEAM @maximilianrang

**Comment by Sacha96** [comment]
@maximilianrang next time would appreciate a conversation before changes. The name attributions were well thought of. Let's move with Team please, as employees seem very formal as pointed out by Kristine.

**Comment by Vilnite** [comment]
@ehab-hassan please update team page for both Foundation and Grid websites accordingly:

![Screenshot 2020-08-07 at 13 58 56](https://user-images.githubusercontent.com/20182572/89639762-d9538b80-d8b6-11ea-82b9-cb3a48c93e1e.png)

![Screenshot 2020-08-07 at 14 01 26](https://user-images.githubusercontent.com/20182572/89639767-dc4e7c00-d8b6-11ea-90ca-d351287f2016.png)

Ambassadors stays as they are for now :)

Thank you.

**Comment by Vilnite** [comment]
Plus footer and header update (same as for the rest of the pages) on team pages for both websites
