### ISSUE TITLE
FOOTER - Updates

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#78]
**Individuals**
What is ThreeFold? -> delete
What is the ThreeFold Token (TFT)? -> delete

**Developers**
Get Started -> delete
add -> Capacity Marketplace (Link to Marketplace)
Developer Resources 
ThreeFold Github

**Ecosystem**
no changes

**About ThreeFold.io**
About Us -> delete
Privacy Policy  -> update as discussed
Terms Of Use  -> update as discussed
add -> Disclaimer as discussed
Contact

**Comment by Vilnite** [comment]
Made all the changes on dev branch. Still need to link all legal stuff (PP, TC, Disclaimer) will do as soon as it's pushed on wiki production.

- [x] check if links are correct/working for the whole footer

**Comment by Vilnite** [comment]
done
