### ISSUE TITLE
Correct some issues with titles & subtitles

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_cloud_threefold.io#82]
@Vilnite Please handle what you can & then re-assign the rest to @ehab-hassan.

- [x] Line Break Issue on Home page header (& on Deploy)
<img width="712" alt="Screen Shot 2020-08-07 at 10 41 49 AM" src="https://user-images.githubusercontent.com/50134479/89621807-43a60500-d892-11ea-9dbb-56115955fbf7.png">
<img width="459" alt="Screen Shot 2020-08-07 at 10 46 40 AM" src="https://user-images.githubusercontent.com/50134479/89622194-f24a4580-d892-11ea-8e0e-eb289c13b41a.png">

- [x] About Us: What We Stand For bigger than Built on Values (Check for Sizing issues across pages)
<img width="873" alt="Screen Shot 2020-08-07 at 10 43 27 AM" src="https://user-images.githubusercontent.com/50134479/89621959-88ca3700-d892-11ea-93f1-ccef4b86d968.png">
<img width="466" alt="Screen Shot 2020-08-07 at 10 46 09 AM" src="https://user-images.githubusercontent.com/50134479/89622152-df377580-d892-11ea-9692-19ce12ccf2ad.png">

- [x] Some titles, across pages, are pure black and some are a slightly lighter black
<img width="937" alt="Screen Shot 2020-08-07 at 10 44 33 AM" src="https://user-images.githubusercontent.com/50134479/89622035-abf4e680-d892-11ea-9e3b-dcce508a4423.png">

- [x] Titles should not end with "." Subtitles should end with "." Example below.
<img width="485" alt="Screen Shot 2020-08-07 at 10 45 28 AM" src="https://user-images.githubusercontent.com/50134479/89622096-c4650100-d892-11ea-8610-3573d5ced367.png">

**Comment by Vilnite** [comment]
Won't be able to help with CSS stuff here.. That's on @ehab-hassan

**Comment by samtaggart** [comment]
Alright thank you @Vilnite! @ehab-hassan When you are back in, please handle these things. Thank you!

**Comment by ehab-hassan** [comment]
done
