### ISSUE TITLE
Update the Title in the partners section in the home page 

### ISSUE THREAD

**Issue by BenjellounO** [threefoldfoundation/www_cloud_threefold.io#91]
In the "partners" section on the homepage, the title is currently: "Hosted on the ThreeFold grid "

As we want to be more specific, we should update it to " Partners Building on the ThreeFold Grid" ( or any other suggestion, that not imply that they fully hosted on the grid)

**Comment by maximilianrang** [comment]
- [x] Please change "Hosted on the ThreeFold grid" -> "Utilizing the ThreeFold Grid"
