### ISSUE TITLE
Include testimonials from our Tech and ACI partners 

### ISSUE THREAD

**Issue by BenjellounO** [threefoldfoundation/www_cloud_threefold.io#92]
To do: 

Ask for testimonials from our closest partners, Tech/Blockchain partners, and our ACI partners, so that we can include them on the ThreeFold.io site.

**Comment by BenjellounO** [comment]
To be completed: https://docs.google.com/document/d/1xja7ifeQbE5edZaFCZGmCMVPJAXdynfRMDlbhlcSJ4Y/edit?usp=sharing

**Comment by maximilianrang** [comment]
This was resolved within another issue. Testimonials are online: https://www.threefold.io/public/#/partners
