### ISSUE TITLE
All subpages : Increase vertical space between sections

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_cloud_threefold.io#94]
The current iteration leaves to little space above headlines. We need to get much closer to the designs that Zia provided. Please use them as a reference and increase the space accordingly.

**Comment by ehab-hassan** [comment]
design at web is different than illustration or design programs at web it related to grid and how it ll be responsive with all sizes 
in bootstrap 4 it related with fixed padding and margin like 1-5 changing this value ll not response good with all size of screen

**Comment by ehab-hassan** [comment]
please more details in this issue or example ,we made equal space between each section

**Comment by maximilianrang** [comment]
Please see the Illustrator files provided by Zia for the exact specification regarding the spacings. We need to  approximate those as much as possible.

**Comment by samaradel** [comment]
now spaces increased to bootstrap max

**Comment by ehab-hassan** [comment]
@maximilianrang @Sacha96 what is status here did we still need space between sections ?

**Comment by maximilianrang** [comment]
Works for me in the current state. What do you think @Sacha96 ?

**Comment by maximilianrang** [comment]
all good now.
