### ISSUE TITLE
TOKEN page: CTA buttons

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_cloud_threefold.io#97]
Suggestion:

![Screenshot 2020-08-11 at 10 12 58](https://user-images.githubusercontent.com/20182572/89868652-d826a500-dbbb-11ea-949b-4185f8891818.png)
![Screenshot 2020-08-11 at 10 16 13](https://user-images.githubusercontent.com/20182572/89868658-da88ff00-dbbb-11ea-9b5a-a0e4e90ee4ce.png)

@maximilianrang please review and assign if accept

**Comment by maximilianrang** [comment]
input merged into https://github.com/threefoldfoundation/www_tfgrid/issues/101
Thank you Kristine.
